// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: api/errors.proto

// 定义包名

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 没有权限
	ErrorReason_UNAUTHORIZED ErrorReason = 0
	// 未知错误
	ErrorReason_UNKNOWN ErrorReason = 1
	// 参数错误
	ErrorReason_INVALID_PARAM ErrorReason = 2
	// 数据库错误
	ErrorReason_DB_ERROR ErrorReason = 3
	// 已存在
	ErrorReason_ALREADY_EXISTS ErrorReason = 4
	// 不存在
	ErrorReason_NOT_FOUND ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNAUTHORIZED",
		1: "UNKNOWN",
		2: "INVALID_PARAM",
		3: "DB_ERROR",
		4: "ALREADY_EXISTS",
		5: "NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"UNAUTHORIZED":   0,
		"UNKNOWN":        1,
		"INVALID_PARAM":  2,
		"DB_ERROR":       3,
		"ALREADY_EXISTS": 4,
		"NOT_FOUND":      5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_errors_proto protoreflect.FileDescriptor

var file_api_errors_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x9a, 0x01, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48,
	0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x91, 0x03, 0x12, 0x11,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0xf4,
	0x03, 0x12, 0x17, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x12, 0x0a, 0x08, 0x44, 0x42,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x1a, 0x04, 0xa8, 0x45, 0xf4, 0x03, 0x12, 0x18,
	0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53,
	0x10, 0x04, 0x1a, 0x04, 0xa8, 0x45, 0x99, 0x03, 0x12, 0x13, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x05, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x1a, 0x04, 0xa0,
	0x45, 0xf4, 0x03, 0x42, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x50, 0x01, 0x5a, 0x0d, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_errors_proto_rawDescOnce sync.Once
	file_api_errors_proto_rawDescData = file_api_errors_proto_rawDesc
)

func file_api_errors_proto_rawDescGZIP() []byte {
	file_api_errors_proto_rawDescOnce.Do(func() {
		file_api_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_errors_proto_rawDescData)
	})
	return file_api_errors_proto_rawDescData
}

var file_api_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: api.kratos.v1.ErrorReason
}
var file_api_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_errors_proto_init() }
func file_api_errors_proto_init() {
	if File_api_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_proto_depIdxs,
		EnumInfos:         file_api_errors_proto_enumTypes,
	}.Build()
	File_api_errors_proto = out.File
	file_api_errors_proto_rawDesc = nil
	file_api_errors_proto_goTypes = nil
	file_api_errors_proto_depIdxs = nil
}
